name: DEPLOY

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      forced_version:
        description: 'FORCED_VERSION to use'
        required: true
        type: string

#permissions:
#  contents: write
#  discussions: write

env:
  CI: true
  FORCED_VERSION: ${{ inputs.forced_version || github.ref }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPEUSERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPEPASSWORD }}
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: zulu

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - { name: Checkout, uses: actions/checkout@v3 }
      - { name: Use Node.js 20.x, uses: actions/setup-node@v3, with: { node-version: 20.x } }
      - { name: Set up JDK, uses: actions/setup-java@v3, with: { distribution: "${{ env.JAVA_DISTRIBUTION }}", java-version: "${{ env.JAVA_VERSION }}" } }
      - { name: Replace Gradle Wrapper, run: "sed 's/-all/-bin/g' gradle/wrapper/gradle-wrapper.properties > gradle/wrapper/gradle-wrapper.properties.bak; cp gradle/wrapper/gradle-wrapper.properties.bak gradle/wrapper/gradle-wrapper.properties" }
      - { name: Prepare Gradle, uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc } # v2.8.0
      - { name: Initialize Gradle, run: ./gradlew --no-configuration-cache }

      # To ensure we are fine before staging repository
      - { name: Publish Publications To Maven Local, run: ./gradlew --no-configuration-cache publishToMavenLocal }
      - { name: Start Maven Central Staging Repository, run: ./gradlew --no-configuration-cache startReleasingMavenCentral }
      - { name: Publish Publications To Maven Repository, run: "./gradlew --no-configuration-cache --parallel --max-workers=32 publishAllPublicationsToMavenRepository" }
      - { name: Release to Maven Central, run: ./gradlew --no-configuration-cache releaseMavenCentral }
